create table tb_filme (id int8 generated by default as identity, descricao varchar(255), duracao float8, titulo varchar(255), url_imagem varchar(255), primary key (id));
create table tb_sala (id int8 generated by default as identity, nome varchar(255), qtd_assentos int4 not null, primary key (id));
create table tb_sessao (id int8 generated by default as identity, data varchar(255), hora varchar(255), tipo_animacao varchar(255), tipo_audio varchar(255), valor_ingresso float8, filme_id int8, sala_id int8, primary key (id));
alter table if exists tb_sessao add constraint FKf0edvi4prm7vy5n68mfafnvfb foreign key (filme_id) references tb_filme;
alter table if exists tb_sessao add constraint FKj4mujh0tjwv4wfsy72tc031r3 foreign key (sala_id) references tb_sala;
