INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('MIB: Homens de Preto', 'https://m.media-amazon.com/images/M/MV5BOTlhYTVkMDktYzIyNC00NzlkLTlmN2ItOGEyMWQ4OTA2NDdmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 'A police officer joins a secret organization that polices and monitors extraterrestrial interactions on Earth.',40);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('MIB: Homens de Preto II ', 'https://m.media-amazon.com/images/M/MV5BMTMxNDA0NTMxMV5BMl5BanBnXkFtZTYwMDE2NzY2._V1_UX182_CR0,0,182,268_AL_.jpg', 'Agent J is sent to find Agent K and restore his memory after the re-appearance of a case from K''s past.',50);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('MIB: Homens de Preto III', 'https://m.media-amazon.com/images/M/MV5BMTU2NTYxODcwMF5BMl5BanBnXkFtZTcwNDk1NDY0Nw@@._V1_UX182_CR0,0,182,268_AL_.jpg', 'Pizza Portuguesa com molho especial, mussarela, presunto, ovos e especiarias.Agent J travels in time to M.I.B.''s early days in 1969 to stop an alien from assassinating his friend Agent K and changing history.',70);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('MIB: Homens de Preto - Internacional', 'https://m.media-amazon.com/images/M/MV5BMDZkODI2ZGItYTY5Yi00MTA4LWExY2ItM2ZmNjczYjM0NDg1XkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_UX182_CR0,0,182,268_AL_.jpg', 'The Men in Black have always protected the Earth from the scum of the universe. In this new adventure, they tackle their biggest threat to date: a mole in the Men in Black organization.',60);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('Coringa', 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.',80);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('Vingadores: Ultimato', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX182_CR0,0,182,268_AL_.jpg', 'After the devastating events of Vingadores: Guerra Infinita (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos'' actions and restore balance to the universe.',90);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('Capitã Marvel', 'https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_UX182_CR0,0,182,268_AL_.jpg', 'Carol Danvers becomes one of the universe''s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.',100);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('Shazam!', 'https://m.media-amazon.com/images/M/MV5BYTE0Yjc1NzUtMjFjMC00Y2I3LTg3NGYtNGRlMGJhYThjMTJmXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_UX182_CR0,0,182,268_AL_.jpg', 'A newly fostered young boy in search of his mother instead finds unexpected super powers and soon gains a powerful enemy.',110);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('John Wick 3: Parabellum!', 'https://m.media-amazon.com/images/M/MV5BMDg2YzI0ODctYjliMy00NTU0LTkxODYtYTNkNjQwMzVmOTcxXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX182_CR0,0,182,268_AL_.jpg', 'John Wick is on the run after killing a member of the international assassin''s guild, and with a $14 million price tag on his head, he is the target of hit men and women everywhere.',120);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('Mistério no Mediterrâneo!', 'https://m.media-amazon.com/images/M/MV5BNTA2YTI5YjUtZWI4Zi00NWQ5LWFiYmEtOTBmNTUyNDAwNjllXkEyXkFqcGdeQXVyNjIzNzM4NzA@._V1_UX182_CR0,0,182,268_AL_.jpg', 'A New York cop and his wife go on a European vacation to reinvigorate the spark in their marriage, but end up getting framed and on the run for the death of an elderly billionaire.',130);
INSERT INTO tb_filme (titulo, url_imagem, descricao, duracao) VALUES ('Star Wars: A Ascensão Skywalker!', 'https://m.media-amazon.com/images/M/MV5BMDljNTQ5ODItZmQwMy00M2ExLTljOTQtZTVjNGE2NTg0NGIxXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_UX182_CR0,0,182,268_AL_.jpg', 'Macarrão penne fresco ao dente com tempero especial.',140);

INSERT INTO tb_sala (nome, qtd_assentos) VALUES ('Sala 1', 40);
INSERT INTO tb_sala (nome, qtd_assentos) VALUES ('Sala 2', 50);
INSERT INTO tb_sala (nome, qtd_assentos) VALUES ('Sala 3', 60);